
resources:
  containers:
  - container: lib7842image
    image: 'theol0403/lib7842-image:latest'

jobs:
- job: BuildTemplate
  timeoutInMinutes: 5

  pool:
    vmImage: 'ubuntu-latest'
  container: lib7842image

  steps:
  - checkout: self

  - bash: |
      make
      make template
      mkdir -p artifacts
      cp *.zip artifacts
    displayName: Build Template
  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: artifacts
      artifactName: template
    condition: succeeded()
    displayName: "Publish Template"

  - bash: |
      make
    displayName: Build Arm Binaries

- job: Test
  timeoutInMinutes: 5
  dependsOn: BuildTemplate

  pool:
    vmImage: 'ubuntu-latest'
  container: lib7842image

  steps:
  - checkout: self
  - bash: |
      git submodule update --init --recursive
    displayName: Checkout Submodules

  - bash: |
      cd test/googletest/
      cmake .
      make
    displayName: Build GoogleTest

  - bash: |
      cd test/
      make
    displayName: Build Tests

  - bash: |
      cd test/
      ./bin/main.exe
    displayName: Run Tests

