
resources:
  containers:
  - container: lib7842image
    image: 'theol0403/lib7842-image:latest'

jobs:
- job: Build
  timeoutInMinutes: 5

  pool:
    vmImage: 'ubuntu-latest'
  container: lib7842image

  steps:
  - checkout: self

  - bash: |
      make
      make template
      mkdir -p artifacts
      cp *.zip artifacts
    displayName: Build Template

  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: artifacts
      artifactName: template
    condition: succeeded()
    displayName: "Publish Template"

  - bash: |
      make
    displayName: Build Arm Binaries

  - bash: |
      cd test/
      make
    displayName: Build Tests

  - bash: |
      ./test/bin/main.exe
    displayName: Run Tests

  - bash: |
      valgrind --tool=memcheck --leak-check=full --leak-resolution=med --show-leak-kinds=all --undef-value-errors=yes --track-origins=yes  --error-exitcode=1 --show-reachable=no ./test/bin/main.exe
    displayName: "Run Valgrind"

  - bash: |
      ./cppCheck.sh
    displayName: "Run CppCheck"

  - bash: |
      valgrind --tool=callgrind  --error-exitcode=1 ./test/bin/main.exe
      mkdir -p callgrindOut
      cp callgrind.out.* callgrindOut
    displayName: "Run Callgrind"

  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: callgrindOut
      artifactName: callgrind
    condition: succeeded()
    displayName: "Publish Callgrind"
