jobs:
- job: Build
  
  pool:
    vmImage: 'ubuntu-latest'

  container: 'theol0403/lib7842-image:latest'

  steps:

  # checkout repo
  - checkout: self
  - bash: |
      git submodule update --init --recursive
    displayName: Download Submodules

  # make template
  - bash: |
      make
      make template
      mkdir -p artifacts
      cp *.zip artifacts
    displayName: Build template
  # publish template
  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: artifacts
      artifactName: template
    condition: succeeded()
    displayName: "Publish Template"

  # make
  - bash: |
      make
    displayName: Build binaries

  # build google
  - bash: |
      cd test/googletest/
      cmake .
      make
    displayName: Build GoogleTest

  # build tests
  - bash: |
      cd test/
      make
    displayName: Build Tests

