jobs:
- job: BuildTemplate
  variables:
    toolchain_update_short: 8-2019q3
    toolchain_update: 8-2019-q3
    toolchain: https://developer.arm.com/-/media/Files/downloads/gnu-rm/$(toolchain_update_short)/RC1.1/gcc-arm-none-eabi-$(toolchain_update)-update-linux.tar.bz2
    pros-cli-v5: https://github.com/purduesigbots/pros-cli/releases/download/3.1.4/pros_cli_v5-3.1.4-py3-none-any.whl
  pool:
    vmImage: 'ubuntu-16.04'
  steps:

  # # install tools
  - script: |
     sudo apt install cmake valgrind -y
    displayName: Install Tools
